### ISSUE TITLE
General idea available

### ISSUE THREAD

**Issue by chseifert** [SECH-Tag-EEXCESS-Browser/Documentation#1]
Do you have already a draft of what the client is expected to do? It would be nice to know and would help to estimate whether we need to consider something additionally when developing server components.

**Comment by pstoehr** [comment]
We are currently working on it. The first version is estimated for end of the week!

**Comment by pstoehr** [comment]
Before working on a night shift we were able to create the first version of the introduction. The requested information can be found at page 6 of the document.
If you have any problems generating the pdf feel free to contact me!

**Comment by chseifert** [comment]
Works like a charm, thx.
