### ISSUE TITLE
Dokumentations Teile überprüfen

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/Documentation#10]
Bitte mal das PDF korrekturlesen und schauen ob alles passt, funktioniert, angezeigt wird, etc. …
@SECH-Tag-EEXCESS-Browser/team-ui 
@SECH-Tag-EEXCESS-Browser/team-content

**Comment by GvRecum** [comment]
Dokumentation aktualisiert, bitte ALLE Korrekturlesen und Feedback geben.

**Comment by pstoehr** [comment]
Ganz schnelles Feedback

Code in der Signatur wohl nicht sinnvoll (Seite 14)
Einleitung bei 7.2 ...
Abbildungen 7.3, 7.4, 7.5, 7.6, 
Gehören Kapitel 8 und Kapitel 14 zusammen?
Tippfehler auf Seiten 39 und  40
15.4. ist leer

Fehler beim LaTeXen
LaTeX Warning: There were multiply-defined labels.
Siehe auch Spec.log:
LaTeX Warning: Label `fig:Hochformat' multiply defined.

**Comment by GvRecum** [comment]
Korrekturen eingepflegt, hoffe, das passt so?
