### ISSUE TITLE
Infos über die beiden Teilteams in intro.tex hinzufügen

### ISSUE THREAD

**Issue by pstoehr** [SECH-Tag-EEXCESS-Browser/Documentation#2]
Sollte auch Brian Mairhoermann zugewiesen werden, nur unter welchem Nickname verbirgt er sich?

**Comment by GvRecum** [comment]
wie kann man denn mehrere Leute hinzufügen?

**Comment by pstoehr** [comment]
Es gibt immer nur einen Bearbeiter für pro Zeitpunkt ...

**Comment by GvRecum** [comment]
Ok, Brian Mairhörmann ist @feres21

**Comment by pstoehr** [comment]
Dann machen Sie mal den Part für ihr Team und dann "assignen" Sie den Issue bitte an "Feres21" ...

**Comment by bmairhoermann** [comment]
Guten Abend die Herren

**Comment by GvRecum** [comment]
Team:Content eingetragen.

**Comment by bmairhoermann** [comment]
Da mein Latex mir die intro.tex nicht ordentlich öffnen will habe ich meine Teambeschreibung und Aufgabenverteilung in der TeamUI_Aufgabenverteilung.tex verfasst.
Hoffe das passt so @GvRecum ?

**Comment by pstoehr** [comment]
Was heißt "nicht ordentlich" öffnen will denn genau? 
Gibt's denn ne Fehlermeldung oder sonst nen sachdienlichen Hinweis?

**Comment by bmairhoermann** [comment]
Hatte das mit Herrn Recum schon besprochen. Es gibt Konflikte mit der Codierung (UTF8), was dazu führt dass mein Texmaker Fehlermeldungen ausspuckt und ich die Datei nicht komplilieren kann.
Hatte mich mit Herrn Recum darauf geeinigt, dass er dann die externen Dateien einbindet.

**Comment by GvRecum** [comment]
schaue ich mir morgen gerne an.
