### ISSUE TITLE
Sech-Meta Änderung

### ISSUE THREAD

**Issue by drui** [SECH-Tag-EEXCESS-Browser/Documentation#4]
Alt:  
`<sech-meta topic="test1" type="misc" mediaType="unknown" provider="ZBW" license="restricted">`

Neu:
HTML Metatag verwenden
`<meta name="sech:topic" content="test1"/>`
`<meta name="sech:type" content="misc"/>`
`<meta name="sech:mediaType" content="unknown"/>`
`<meta name="sech:provide" content="ZBW"/>`
`<meta name="sech:license" content="restricted"/>`

**Comment by GvRecum** [comment]
Wenn dann:

``` html
<meta name="sech" content="topic=test1, type=misc, mediaType=unknown, provider=ZBW, license=restricted">
```

(ein Tag und ohne schließendes /)
vgl.:
https://wiki.selfhtml.org/wiki/HTML/Kopfdaten/meta#Viewport_einstellen

…macht den SECH-Meta Tag jetzt aber nicht unbedingt einfacher.

**Comment by drui** [comment]
Ich hab die Tags einfach nach Beispiel von den Twitter Metatags erstellt, also
`<meta name="twitter:card" content="summary"/>`
`<meta name="twitter:description" content="qwe"/>`
`<meta name="twitter:title" content="asd>`
`<meta name="twitter:domain" content="yxc"/>`

Sind meiner Meinung nach so leichter zu lesen und zu erstellen. Und mehrer Informationen in einen Tag zu legen macht es nur wieder unübersichtlich und man kann es direkt beim alten lassen.

Das schließende / ist auf der Seite auf der ich war überall. Es macht auch keinen Unterschied ob man es macht oder nicht.

**Comment by bmairhoermann** [comment]
Also rein analysetechnisch wäre es mir angenehmer, wenn sich die Attribute innerhalb eines sech-meta-tags befinden, da diese schreibweise, wie Fred sie vorgeschlagen hat, der der anderen sech-tags gleicht.

Die Frage ist ob die Fred-Schreibweise ein grober Verstoß gegen die html5-Richtlinien ist?

**Comment by drui** [comment]
Die Parameter im Browser auslesen wird durch getrennte Tags weder leichter noch schwerer. 
Aber im Code ist es übersichtlicher wenn man nur kurze Zeilen hat. (die restlichen Sechtags sind meiner Meinung nach auch viel zu lang)

Es ist erlaubt mehr als ein Parameter in content zu schreiben, aber es wird nicht oft gemacht.

**Comment by GvRecum** [comment]
Die Informationen hängen ja aber alle zusammen, einzelne meta Tags zu kreieren reisst das alles auseinander.
Was zum Beispiel bewirkt ein 

``` html
<meta name="sech:mediaType" content="unknown">
```

ohne ein 

``` html
<meta name="sech:topic" content="test1">
```

Es wird schwieriger zu überprüfen was fehlt. Was ist, wenn der Ersteller die meta Tags nicht beisammen hält, sondern verstreut? Klar ist es nicht schön, aber die Attribute müssen ja nicht alle benutzt werden, es sind lediglich alle optionalen Attribute versammelt.

``` html
<meta name="sech" content="topic=test1">
```

ist doch schon viel übersichtlicher.

Randnotiz: meine Schreibweise ist HTML5 konform, der Unterschied zwischen `</sech>` und `/>` ist das X in XHTML.

**Comment by GvRecum** [comment]
Lösungsvorschlag:

Umbenennung in SECH-Head-Tag `<sech-head>` um Meta-Charakter/-Verwechslung zu vermeiden, aber korrekte Verortung zu gewährleisten..

Bitte am Freitag abstimmen und entscheiden.
@SECH-Tag-EEXCESS-Browser/team-content 
@SECH-Tag-EEXCESS-Browser/team-ui
